Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Aabb))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Basis))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Color))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Plane))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Quat))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Rect2))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Transform))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Transform2D))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Vector2))
Godot::Generator::Class.register_class(Godot::Generator::Class::Stack.new(:Vector3))

Godot::Generator::Class.register_class(Godot::Generator::Class::Array.new)
Godot::Generator::Class.register_class(Godot::Generator::Class::Dictionary.new)
Godot::Generator::Class.register_class(Godot::Generator::Class::NodePath.new)
Godot::Generator::Class.register_class(Godot::Generator::Class::Object.new)
Godot::Generator::Class.register_class(Godot::Generator::Class::PoolStringArray.new)
Godot::Generator::Class.register_class(Godot::Generator::Class::String.new)
