#include <gdnative_api_struct.gen.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ruby.h>
#include "godot-ruby/debug.h"
#include "godot-ruby/generated/built_in_types.c"
#include "godot-ruby/pluginscript.c"
#include "godot-ruby/debug.c"
